package Presentacion.ListaDeReproduccion;

public class frmAltaListaDeReproduccion extends javax.swing.JDialog {

    public frmAltaListaDeReproduccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jLabel100 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        jScrollPane31 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList<>();
        rbPublica = new javax.swing.JRadioButton();
        rbPrivada = new javax.swing.JRadioButton();
        jLabel102 = new javax.swing.JLabel();
        jScrollPane32 = new javax.swing.JScrollPane();
        lstUsuarios = new javax.swing.JList<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlTipo = new javax.swing.JPanel();
        rbPorDefecto = new javax.swing.JRadioButton();
        rbParticular = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva lista de reproduccion");

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel100.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel100.setText("Nombre:");
        jPanel17.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));
        jPanel17.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 300, -1));

        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel101.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel101.setText("Usuarios:");
        jPanel18.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jScrollPane31.setViewportView(lstCategorias);

        jPanel18.add(jScrollPane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 340, 180));

        rbPublica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPublica.setText("Publica");
        jPanel18.add(rbPublica, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        rbPrivada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPrivada.setText("Privada");
        jPanel18.add(rbPrivada, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jLabel102.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel102.setText("Categoria:");
        jPanel18.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jScrollPane32.setViewportView(lstUsuarios);

        jPanel18.add(jScrollPane32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 320, 180));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 750, 270));

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel17.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 370, 40));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel17.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 350, 40));

        pnlTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
        pnlTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlTipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbPorDefecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPorDefecto.setText("Por defecto");
        rbPorDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPorDefectoActionPerformed(evt);
            }
        });
        pnlTipo.add(rbPorDefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        rbParticular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbParticular.setText("Particular");
        rbParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParticularActionPerformed(evt);
            }
        });
        pnlTipo.add(rbParticular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel17.add(pnlTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 10, 330, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        //lista_rep->nueva_list_rep->aceptar
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //lista_rep->nueva_list_rep->cancelar
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbPorDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPorDefectoActionPerformed
        if (rbParticular.isSelected()) {
            jPanel18.setVisible(true);
        } else {
            jPanel18.setVisible(false);
        }
    }//GEN-LAST:event_rbPorDefectoActionPerformed

    private void rbParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbParticularActionPerformed
        if (rbParticular.isSelected()) {
            jPanel18.setVisible(true);
        } else {
            jPanel18.setVisible(false);
        }
    }//GEN-LAST:event_rbParticularActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JList<String> lstCategorias;
    private javax.swing.JList<String> lstUsuarios;
    private javax.swing.JPanel pnlTipo;
    private javax.swing.JRadioButton rbParticular;
    private javax.swing.JRadioButton rbPorDefecto;
    private javax.swing.JRadioButton rbPrivada;
    private javax.swing.JRadioButton rbPublica;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
